STEP 1: Load data
STEP 2: Create Bigrams
STEP 3: Perform One-hot encoding
STEP 4: Create model and train
STEP 5: Visualize results

# Loading Data

In [33]:
file = open(r'C:\Users\Bildad Otieno\Documents\Billy_Repo\Understanding_LSTM\royal_data.txt')


In [34]:
royal_data = file.readlines()

In [35]:
print(royal_data[1])

Daughter is the princess



In [36]:
for idx, val in enumerate(royal_data):
    royal_data[idx] = val.lower().replace("\n","")

In [37]:
print(royal_data)

['the future king is the prince', 'daughter is the princess', 'son is the prince', 'only a man can be a king', 'only a woman can be a queen', 'the princess will be a queen', 'the prince is a strong man', 'the princess is a beautiful woman', 'prince is only a boy now', 'prince will be a king', 'a boy will be a man']


# Remove Stopwords and Tokenize

In [38]:
stopwords = ['the', 'is', 'are', 'can', 'will', 'be', 'a', 'now', 'only', 'their', 'and', 'at', 'it']



In [39]:
filter_data = []


for sentence in royal_data:
    temp = []
    for word in sentence.split(): 
        if word not in stopwords:
            temp.append(word)
    filter_data.append(temp)
       

In [40]:
filter_data

[['future', 'king', 'prince'],
 ['daughter', 'princess'],
 ['son', 'prince'],
 ['man', 'king'],
 ['woman', 'queen'],
 ['princess', 'queen'],
 ['prince', 'strong', 'man'],
 ['princess', 'beautiful', 'woman'],
 ['prince', 'boy'],
 ['prince', 'king'],
 ['boy', 'man']]

# Creating Bigrams

In [41]:
bigrams = []

for a_list in filter_data:
    for i in range(0,(len(a_list))-1):
        for j in range(i+1, len(a_list)):
            bigrams.append([a_list[i], a_list[j]])
            bigrams.append([a_list[j], a_list[i]])

In [42]:
bigrams

[['future', 'king'],
 ['king', 'future'],
 ['future', 'prince'],
 ['prince', 'future'],
 ['king', 'prince'],
 ['prince', 'king'],
 ['daughter', 'princess'],
 ['princess', 'daughter'],
 ['son', 'prince'],
 ['prince', 'son'],
 ['man', 'king'],
 ['king', 'man'],
 ['woman', 'queen'],
 ['queen', 'woman'],
 ['princess', 'queen'],
 ['queen', 'princess'],
 ['prince', 'strong'],
 ['strong', 'prince'],
 ['prince', 'man'],
 ['man', 'prince'],
 ['strong', 'man'],
 ['man', 'strong'],
 ['princess', 'beautiful'],
 ['beautiful', 'princess'],
 ['princess', 'woman'],
 ['woman', 'princess'],
 ['beautiful', 'woman'],
 ['woman', 'beautiful'],
 ['prince', 'boy'],
 ['boy', 'prince'],
 ['prince', 'king'],
 ['king', 'prince'],
 ['boy', 'man'],
 ['man', 'boy']]

In [43]:
every_word = []

for sentence in bigrams:
    for word in sentence:    
        every_word.append(word)

In [44]:
every_word

['future',
 'king',
 'king',
 'future',
 'future',
 'prince',
 'prince',
 'future',
 'king',
 'prince',
 'prince',
 'king',
 'daughter',
 'princess',
 'princess',
 'daughter',
 'son',
 'prince',
 'prince',
 'son',
 'man',
 'king',
 'king',
 'man',
 'woman',
 'queen',
 'queen',
 'woman',
 'princess',
 'queen',
 'queen',
 'princess',
 'prince',
 'strong',
 'strong',
 'prince',
 'prince',
 'man',
 'man',
 'prince',
 'strong',
 'man',
 'man',
 'strong',
 'princess',
 'beautiful',
 'beautiful',
 'princess',
 'princess',
 'woman',
 'woman',
 'princess',
 'beautiful',
 'woman',
 'woman',
 'beautiful',
 'prince',
 'boy',
 'boy',
 'prince',
 'prince',
 'king',
 'king',
 'prince',
 'boy',
 'man',
 'man',
 'boy']

In [45]:
unique_words = set(every_word)
unique_words

{'beautiful',
 'boy',
 'daughter',
 'future',
 'king',
 'man',
 'prince',
 'princess',
 'queen',
 'son',
 'strong',
 'woman'}

In [46]:
unique_words = list(unique_words)

In [47]:
unique_words.sort()
unique_words

['beautiful',
 'boy',
 'daughter',
 'future',
 'king',
 'man',
 'prince',
 'princess',
 'queen',
 'son',
 'strong',
 'woman']

# One-hot Encoding

In [48]:
words_dict = {}

counter = 0
for word in unique_words:
    words_dict[word] = counter
    counter+=1

In [49]:
print(words_dict)

{'beautiful': 0, 'boy': 1, 'daughter': 2, 'future': 3, 'king': 4, 'man': 5, 'prince': 6, 'princess': 7, 'queen': 8, 'son': 9, 'strong': 10, 'woman': 11}


In [50]:
import numpy as np

one_hot_data = np.zeros((len(unique_words),len(unique_words)))

In [51]:
one_hot_data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
for i in range(len(unique_words)):
    one_hot_data[i][i]= 1

In [53]:
unique_words[0]

'beautiful'

In [54]:
one_hot_dict = {}
for i in range(len(unique_words)):
    one_hot_dict[unique_words[i]] = one_hot_data[i]

for word in one_hot_dict:
    print(word, " : ", one_hot_dict[word])

beautiful  :  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
boy  :  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
daughter  :  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
future  :  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
king  :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
man  :  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
prince  :  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
princess  :  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
queen  :  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
son  :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
strong  :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
woman  :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [55]:
print(one_hot_dict['beautiful'])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
bigrams

[['future', 'king'],
 ['king', 'future'],
 ['future', 'prince'],
 ['prince', 'future'],
 ['king', 'prince'],
 ['prince', 'king'],
 ['daughter', 'princess'],
 ['princess', 'daughter'],
 ['son', 'prince'],
 ['prince', 'son'],
 ['man', 'king'],
 ['king', 'man'],
 ['woman', 'queen'],
 ['queen', 'woman'],
 ['princess', 'queen'],
 ['queen', 'princess'],
 ['prince', 'strong'],
 ['strong', 'prince'],
 ['prince', 'man'],
 ['man', 'prince'],
 ['strong', 'man'],
 ['man', 'strong'],
 ['princess', 'beautiful'],
 ['beautiful', 'princess'],
 ['princess', 'woman'],
 ['woman', 'princess'],
 ['beautiful', 'woman'],
 ['woman', 'beautiful'],
 ['prince', 'boy'],
 ['boy', 'prince'],
 ['prince', 'king'],
 ['king', 'prince'],
 ['boy', 'man'],
 ['man', 'boy']]

In [57]:
X = []
Y = []

for bi in bigrams:
    X.append(one_hot_dict[bi[0]])
    Y.append(one_hot_dict[bi[1]])

In [58]:
X = np.array(X)
Y = np.array(Y)

# Creating Model

In the input layer and output layer the number of neurons will be the same.

Number of neurons will be same as the unique words, in our case 12.

Number of hidden layers will be 2, as our word embedding vector size. It will also be useful as we will be plotting a scatter plot which is a 2D graph.

The graph will help us understand whether our word embeddings are properly trained or not.

In [59]:
from keras.models import Sequential
from keras.layers import Dense, Input

# Creating 2 variable which will help take care of any kind of size model might take

vocab_size = len(one_hot_data[0]) # Will be the length of that one-hot vector
embedding_size = 2

model = Sequential([
    
    Input(shape=(vocab_size,)), # Because that is the size of our One-hot Encoding
    Dense(embedding_size, activation= 'linear'), # Which means we do not want to use any activation function
    Dense(vocab_size, activation='Softmax') 
    
])


In [60]:

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam')


In [61]:

model.fit(X,Y, epochs = 1000)

Epoch 1/1000
2/2 [==============================] - 2s 12ms/step - loss: 2.4919
Epoch 2/1000
2/2 [==============================] - 0s 9ms/step - loss: 2.4898
Epoch 3/1000
2/2 [==============================] - 0s 25ms/step - loss: 2.4881
Epoch 4/1000
2/2 [==============================] - 0s 22ms/step - loss: 2.4867
Epoch 5/1000
2/2 [==============================] - 0s 8ms/step - loss: 2.4853
Epoch 6/1000
2/2 [==============================] - 0s 11ms/step - loss: 2.4838
Epoch 7/1000
2/2 [==============================] - 0s 25ms/step - loss: 2.4824
Epoch 8/1000
2/2 [==============================] - 0s 6ms/step - loss: 2.4810
Epoch 9/1000
2/2 [==============================] - 0s 10ms/step - loss: 2.4797
Epoch 10/1000
2/2 [==============================] - 0s 134ms/step - loss: 2.4784
Epoch 11/1000
2/2 [==============================] - 0s 13ms/step - loss: 2.4771
Epoch 12/1000
2/2 [==============================] - 0s 7ms/step - loss: 2.4758
Epoch 13/1000
2/2 [=====================

In [62]:
weights = model.get_weights()[0] # By specifying index 0, we are targetting the weights betweeen the hidden layer and output layer

weights

array([[-0.8854749 , -0.8461896 ],
       [ 0.55531013,  1.2030673 ],
       [-1.1466458 , -1.2204363 ],
       [ 0.8695936 ,  0.10893974],
       [ 0.93862945,  1.1888406 ],
       [ 0.7175948 , -0.74283385],
       [ 1.0112175 , -0.6210684 ],
       [-1.1284871 ,  0.9527748 ],
       [-1.2766173 , -0.73739517],
       [ 0.6992936 ,  0.41050828],
       [ 0.41525307,  0.695303  ],
       [-1.1685997 ,  0.18300836]], dtype=float32)

The first word embeddings **[-1.4604876 , -0.07536481]** are mapped to the word **'beautiful'**

In [64]:
word_embeddings = {} #Creating this dictionary to map words to their corresponding embedding

for word in unique_words:
    word_embeddings[word] = weights[words_dict[word]]

In [71]:
for word in word_embeddings:
    print(word, " : " ,word_embeddings[word])

beautiful  :  [-0.8854749 -0.8461896]
boy  :  [0.55531013 1.2030673 ]
daughter  :  [-1.1466458 -1.2204363]
future  :  [0.8695936  0.10893974]
king  :  [0.93862945 1.1888406 ]
man  :  [ 0.7175948  -0.74283385]
prince  :  [ 1.0112175 -0.6210684]
princess  :  [-1.1284871  0.9527748]
queen  :  [-1.2766173  -0.73739517]
son  :  [0.6992936  0.41050828]
strong  :  [0.41525307 0.695303  ]
woman  :  [-1.1685997   0.18300836]


In [76]:
from matplotlib import pyplot as plt

In [77]:
coord = word_embeddings['beautiful']

In [80]:
coord[1]

-0.8461896

In [81]:
plt.scatter(coord[0],coord[1])

: 